title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://m0n-k1y.github.io/just-the-docs-demo

aux_links:
  Template Repository: https://github.com/m0n-k1y/just-the-docs-demo
